import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import { getCurrentUser } from "@/lib/session"; // adjust if path differs

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "School CBT System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = getCurrentUser();

  // Determine userRole for Navbar links
  const userRole = user?.role ?? "student"; // default fallback

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen flex flex-col bg-gray-50 text-gray-900">
          {/* Navbar */}
          <Navbar userRole={userRole} />

          {/* Main Content */}
          <main className="flex-1 px-6 py-8 max-w-6xl mx-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
